[package]
name = "quicksort"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
panic = 'abort'
codegen-units = 1
target-cpu = "native"

[dependencies]

[lib]
crate-type = ["cdylib"]  # This is the key part, specifying the shared library
